from no_strategy_simsiam import NoStrategySimSiam
from no_strategy_byol import NoStrategyBYOL
from no_strategy_barlow_twins import NoStrategyBarlowTwins
from .replay_simsiam import ReplaySimSiam
from .replay_byol import ReplayBYOL
from .replay_barlow_twins import ReplayBarlowTwins